// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAElT4BJxsrDROG2Q7lyzjilYxE9_-HrUw',
    appId: '1:36846423389:web:a8a598ffbeb46012e9acb4',
    messagingSenderId: '36846423389',
    projectId: 'inventoryproductmanageme-b3992',
    authDomain: 'inventoryproductmanageme-b3992.firebaseapp.com',
    storageBucket: 'inventoryproductmanageme-b3992.firebasestorage.app',
    measurementId: 'G-9M2XG2WM3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK27IC0Jlvk564kVDf3MMqbjaKYRrI5lQ',
    appId: '1:36846423389:android:ed4de1ed81b1004de9acb4',
    messagingSenderId: '36846423389',
    projectId: 'inventoryproductmanageme-b3992',
    storageBucket: 'inventoryproductmanageme-b3992.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB-3kfb5GUjekqRrYTcjoZZRjqfbsJtyw',
    appId: '1:36846423389:ios:6dfc3630e2254ab3e9acb4',
    messagingSenderId: '36846423389',
    projectId: 'inventoryproductmanageme-b3992',
    storageBucket: 'inventoryproductmanageme-b3992.firebasestorage.app',
    iosBundleId: 'com.example.inventoryproductapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB-3kfb5GUjekqRrYTcjoZZRjqfbsJtyw',
    appId: '1:36846423389:ios:6dfc3630e2254ab3e9acb4',
    messagingSenderId: '36846423389',
    projectId: 'inventoryproductmanageme-b3992',
    storageBucket: 'inventoryproductmanageme-b3992.firebasestorage.app',
    iosBundleId: 'com.example.inventoryproductapp',
  );
}
